// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _21cb728274153f54c8abde62f5c205eb_7111738075838154005 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Byte hasDriver;
            [FieldOffset(1)]
            public System.Byte hasPassenger;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _21cb728274153f54c8abde62f5c205eb_7111738075838154005.hasDriverMask;
            hasDriverSimulationFrame = frame;
            FieldsMask |= _21cb728274153f54c8abde62f5c205eb_7111738075838154005.hasPassengerMask;
            hasPassengerSimulationFrame = frame;
        }

        public static unsafe _21cb728274153f54c8abde62f5c205eb_7111738075838154005 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 2) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 2) " +
                    "for component with ID 26");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 26");
            }

            var orig = new _21cb728274153f54c8abde62f5c205eb_7111738075838154005();

            var comp = (Interop*)data;

            orig.hasDriver = comp->hasDriver != 0;
            orig.hasPassenger = comp->hasPassenger != 0;

            return orig;
        }


        public static uint hasDriverMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame hasDriverSimulationFrame;
        public System.Boolean hasDriver;
        public static uint hasPassengerMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame hasPassengerSimulationFrame;
        public System.Boolean hasPassenger;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 26;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000011;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 2;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;


        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_21cb728274153f54c8abde62f5c205eb_7111738075838154005)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.hasDriverSimulationFrame = other.hasDriverSimulationFrame;
                this.hasDriver = other.hasDriver;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.hasPassengerSimulationFrame = other.hasPassengerSimulationFrame;
                this.hasPassenger = other.hasPassenger;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_21cb728274153f54c8abde62f5c205eb_7111738075838154005 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 2);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.hasDriver;
                bitStream.WriteBool(fieldValue);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.hasPassenger;
                bitStream.WriteBool(fieldValue);
            }
            mask >>= 1;

            return mask;
        }

        public static _21cb728274153f54c8abde62f5c205eb_7111738075838154005 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(2);
            }

            var val = new _21cb728274153f54c8abde62f5c205eb_7111738075838154005();
            if (bitStream.ReadMask())
            {

                val.hasDriver = bitStream.ReadBool();
                val.FieldsMask |= _21cb728274153f54c8abde62f5c205eb_7111738075838154005.hasDriverMask;
            }
            if (bitStream.ReadMask())
            {

                val.hasPassenger = bitStream.ReadBool();
                val.FieldsMask |= _21cb728274153f54c8abde62f5c205eb_7111738075838154005.hasPassengerMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_21cb728274153f54c8abde62f5c205eb_7111738075838154005(" +
                $" hasDriver: { this.hasDriver }" +
                $" hasPassenger: { this.hasPassenger }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(2, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(2, '0') })";
        }
    }

}
