// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _21cb728274153f54c8abde62f5c205eb_5dc56a424798449c8671b425fa6ac326 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Entity requester;
        }

        public static unsafe _21cb728274153f54c8abde62f5c205eb_5dc56a424798449c8671b425fa6ac326 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 4) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 4) " +
                    "for command with ID 6");
            }

            var orig = new _21cb728274153f54c8abde62f5c205eb_5dc56a424798449c8671b425fa6ac326();
            var comp = (Interop*)data;
            orig.requester = comp->requester;
            return orig;
        }

        public Entity requester;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Target { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        public uint GetComponentType() => 6;
        public bool UsesMeta { get; set; }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(requester, false, out absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.requester = absoluteEntity;
            
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            err = mapper.MapToRelativeEntity(requester, false, out relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.requester = relativeEntity;
            
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return new HashSet<Entity> {
                this.requester,
            };
        }

        public void NullEntityRefs(Entity entity) {
            if (this.requester == entity) {
                this.requester = Entity.InvalidRelative;
            }
        }
        
        public _21cb728274153f54c8abde62f5c205eb_5dc56a424798449c8671b425fa6ac326(
            Entity entity,
            Entity requester
        )
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Target = default;
            Routing = MessageTarget.All;
            SenderParticipant = 0;
            SenderClientID = default;
            Frame = 0;
            UsesMeta = false;

            this.requester = requester; 
        }
        
        public static void Serialize(_21cb728274153f54c8abde62f5c205eb_5dc56a424798449c8671b425fa6ac326 commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteEntity(commandData.requester);
        }
        
        public static _21cb728274153f54c8abde62f5c205eb_5dc56a424798449c8671b425fa6ac326 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var datarequester = bitStream.ReadEntity();
    
            return new _21cb728274153f54c8abde62f5c205eb_5dc56a424798449c8671b425fa6ac326()
            {
                Entity = entity,
                Routing = target,
                Target = target,
                requester = datarequester
            };   
        }
    }

}
