// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_1dd8420523b64e60836b6cc7a0f6584a : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_7dae4f552b594908aa28854b7bfe6985 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_29e116267a2f4f9c98cec0f76172d2a5 : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_457c58ba37dc46d184bcca934d291f29 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a6f62748104f3194aace021743ab9cc0_437266469125202482);
        public override string CoherenceComponentName => "_a6f62748104f3194aace021743ab9cc0_437266469125202482";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).IsPassenger;

            var simFrame = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).IsPassengerSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.IsPassenger = Value;
            }
            else
            {
                update.IsPassenger = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.IsPassengerSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a6f62748104f3194aace021743ab9cc0_437266469125202482();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_29e88b79fad644369bc2648ed0b9fd96 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a6f62748104f3194aace021743ab9cc0_437266469125202482);
        public override string CoherenceComponentName => "_a6f62748104f3194aace021743ab9cc0_437266469125202482";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).IsDriving;

            var simFrame = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).IsDrivingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.IsDriving = Value;
            }
            else
            {
                update.IsDriving = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.IsDrivingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a6f62748104f3194aace021743ab9cc0_437266469125202482();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_7d60ca5118b24a90a8721aea19741730 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a6f62748104f3194aace021743ab9cc0_437266469125202482);
        public override string CoherenceComponentName => "_a6f62748104f3194aace021743ab9cc0_437266469125202482";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).MotionSpeed;

            var simFrame = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).MotionSpeedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.MotionSpeed = Value;
            }
            else
            {
                update.MotionSpeed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.MotionSpeedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a6f62748104f3194aace021743ab9cc0_437266469125202482();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_9da35fd11f8c43e982f05a3f8c0e88d5 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a6f62748104f3194aace021743ab9cc0_437266469125202482);
        public override string CoherenceComponentName => "_a6f62748104f3194aace021743ab9cc0_437266469125202482";
        public override uint FieldMask => 0b00000000000000000000000000001000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).FreeFall;

            var simFrame = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).FreeFallSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.FreeFall = Value;
            }
            else
            {
                update.FreeFall = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.FreeFallSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a6f62748104f3194aace021743ab9cc0_437266469125202482();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_6011aa9a23de4221961ef4b7ad043110 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a6f62748104f3194aace021743ab9cc0_437266469125202482);
        public override string CoherenceComponentName => "_a6f62748104f3194aace021743ab9cc0_437266469125202482";
        public override uint FieldMask => 0b00000000000000000000000000010000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).Grounded;

            var simFrame = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).GroundedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Grounded = Value;
            }
            else
            {
                update.Grounded = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.GroundedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a6f62748104f3194aace021743ab9cc0_437266469125202482();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_5846ca630ad84e5e8312b59555c55bd4 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a6f62748104f3194aace021743ab9cc0_437266469125202482);
        public override string CoherenceComponentName => "_a6f62748104f3194aace021743ab9cc0_437266469125202482";
        public override uint FieldMask => 0b00000000000000000000000000100000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).Jump;

            var simFrame = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).JumpSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Jump = Value;
            }
            else
            {
                update.Jump = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.JumpSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a6f62748104f3194aace021743ab9cc0_437266469125202482();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_64bc032806e545bfa43b134501afd067 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a6f62748104f3194aace021743ab9cc0_437266469125202482);
        public override string CoherenceComponentName => "_a6f62748104f3194aace021743ab9cc0_437266469125202482";
        public override uint FieldMask => 0b00000000000000000000000001000000;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).Speed;

            var simFrame = ((_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent).SpeedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a6f62748104f3194aace021743ab9cc0_437266469125202482)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Speed = Value;
            }
            else
            {
                update.Speed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SpeedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a6f62748104f3194aace021743ab9cc0_437266469125202482();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_b9d39ff5ba8d426a8abef33ccbce8bc5 : StringBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a6f62748104f3194aace021743ab9cc0_1680387227265687212);
        public override string CoherenceComponentName => "_a6f62748104f3194aace021743ab9cc0_1680387227265687212";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.path); }
            set { CastedUnityComponent.path = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a6f62748104f3194aace021743ab9cc0_1680387227265687212)coherenceComponent).path;

            var simFrame = ((_a6f62748104f3194aace021743ab9cc0_1680387227265687212)coherenceComponent).pathSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a6f62748104f3194aace021743ab9cc0_1680387227265687212)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.path = Value;
            }
            else
            {
                update.path = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.pathSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a6f62748104f3194aace021743ab9cc0_1680387227265687212();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a6f62748104f3194aace021743ab9cc0_7b9bb66d609d42eb9c1a3fac4a989ae0 : IntBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a6f62748104f3194aace021743ab9cc0_1680387227265687212);
        public override string CoherenceComponentName => "_a6f62748104f3194aace021743ab9cc0_1680387227265687212";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.pathDirtyCounter); }
            set { CastedUnityComponent.pathDirtyCounter = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a6f62748104f3194aace021743ab9cc0_1680387227265687212)coherenceComponent).pathDirtyCounter;

            var simFrame = ((_a6f62748104f3194aace021743ab9cc0_1680387227265687212)coherenceComponent).pathDirtyCounterSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a6f62748104f3194aace021743ab9cc0_1680387227265687212)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.pathDirtyCounter = Value;
            }
            else
            {
                update.pathDirtyCounter = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.pathDirtyCounterSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a6f62748104f3194aace021743ab9cc0_1680387227265687212();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_a6f62748104f3194aace021743ab9cc0 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_a6f62748104f3194aace021743ab9cc0>();
        
        private global::PlayerBrain _a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["1dd8420523b64e60836b6cc7a0f6584a"] = new Binding_a6f62748104f3194aace021743ab9cc0_1dd8420523b64e60836b6cc7a0f6584a(),
			["7dae4f552b594908aa28854b7bfe6985"] = new Binding_a6f62748104f3194aace021743ab9cc0_7dae4f552b594908aa28854b7bfe6985(),
			["29e116267a2f4f9c98cec0f76172d2a5"] = new Binding_a6f62748104f3194aace021743ab9cc0_29e116267a2f4f9c98cec0f76172d2a5(),
			["457c58ba37dc46d184bcca934d291f29"] = new Binding_a6f62748104f3194aace021743ab9cc0_457c58ba37dc46d184bcca934d291f29(),
			["29e88b79fad644369bc2648ed0b9fd96"] = new Binding_a6f62748104f3194aace021743ab9cc0_29e88b79fad644369bc2648ed0b9fd96(),
			["7d60ca5118b24a90a8721aea19741730"] = new Binding_a6f62748104f3194aace021743ab9cc0_7d60ca5118b24a90a8721aea19741730(),
			["9da35fd11f8c43e982f05a3f8c0e88d5"] = new Binding_a6f62748104f3194aace021743ab9cc0_9da35fd11f8c43e982f05a3f8c0e88d5(),
			["6011aa9a23de4221961ef4b7ad043110"] = new Binding_a6f62748104f3194aace021743ab9cc0_6011aa9a23de4221961ef4b7ad043110(),
			["5846ca630ad84e5e8312b59555c55bd4"] = new Binding_a6f62748104f3194aace021743ab9cc0_5846ca630ad84e5e8312b59555c55bd4(),
			["64bc032806e545bfa43b134501afd067"] = new Binding_a6f62748104f3194aace021743ab9cc0_64bc032806e545bfa43b134501afd067(),
			["b9d39ff5ba8d426a8abef33ccbce8bc5"] = new Binding_a6f62748104f3194aace021743ab9cc0_b9d39ff5ba8d426a8abef33ccbce8bc5(),
			["7b9bb66d609d42eb9c1a3fac4a989ae0"] = new Binding_a6f62748104f3194aace021743ab9cc0_7b9bb66d609d42eb9c1a3fac4a989ae0(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_a6f62748104f3194aace021743ab9cc0()
        {
            bakedCommandBindings.Add("6dd9a86c087541c99ecb256252565a2f", BakeCommandBinding__a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f_CommandTarget = (global::PlayerBrain)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"PlayerBrain.OnRemoteVehicleResponded",
            	"(System.Boolean)",
            	SendCommand__a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f,
            	ReceiveLocalCommand__a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f,
            	MessageTarget.All,
            	_a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.canEnter = (System.Boolean)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.canEnter = (System.Boolean)requestArgs.Args[0];

            ReceiveCommand__a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f(command);
        }

        private void ReceiveCommand__a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f(_a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f command)
        {
            var target = _a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f_CommandTarget;
			target.OnRemoteVehicleResponded((System.Boolean)(command.canEnter));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f castedCommand:
                    ReceiveCommand__a6f62748104f3194aace021743ab9cc0_6dd9a86c087541c99ecb256252565a2f(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_a6f62748104f3194aace021743ab9cc0 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_a6f62748104f3194aace021743ab9cc0>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
